version: '2.2'
services:
  es01:
    build: 
      context: .
    container_name: es01
    environment:
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic

volumes:
  data01:
    driver: local
  
networks:
  elastic:
    driver: bridge